services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: crud-backend:prod
    container_name: crud_backend
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/cruddb
      - PORT=3000
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - crud_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: crud-frontend:prod
    container_name: crud_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - crud_net

  mongo:
    image: mongo:7
    container_name: crud_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - crud_net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: crud_mongo_express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secret@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - crud_net

volumes:
  mongo_data:

networks:
  crud_net:
    driver: bridge

# include:
#   - backend/docker-compose.yaml
#   - frontend/docker-compose.yaml
