services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: crud-backend:dev
    container_name: crud_backend_dev
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:secret@mongo:27017/cruddb?authSource=admin
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - crud_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: crud-frontend:dev
    container_name: crud_frontend_dev
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - crud_net

  mongo:
    image: mongo:7
    container_name: crud_mongo_dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - crud_net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: crud_mongo_express_dev
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secret@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_SITE_BASEURL=/
    ports:
      - "8082:8081" # پورت متفاوت تا با prod تداخل نکنه
    depends_on:
      - mongo
    networks:
      - crud_net

volumes:
  mongo_data_dev:

networks:
  crud_net:
    driver: bridge
