FROM node:24.18.0-alpine

WORKDIR /app

# nodemon برای hot reload
RUN npm install -g nodemon

# package files
COPY package*.json ./

# همه dependency ها (شامل dev)
RUN npm install

EXPOSE 3000
CMD ["nodemon", "--legacy-watch", "index.js"]